heat_template_version: newton

parameters:
  keyname:
    type: string
    default: mykey
    description: Key pair for password-less login
  imgname:
    type: string

resources:
   fip:
      type: OS::Nova::FloatingIP
      properties:
         pool: public
   fip_assoc:
      type: OS::Nova::FloatingIPAssociation
      properties:
         server_id: { get_resource: myserver }
         floating_ip: { get_resource: fip }

   myserver:
      type: OS::Nova::Server
      properties:
         config_drive: true
         key_name: { get_param: keyname }
         image: { get_param: imgname }
         flavor: 1
         networks:
           - network: 'private'

