heat_template_version: newton

parameters:
  ssh_key:
    type: string
    description: Key pair for password-less login

resources:

   nested_server:
      type: OS::Nova::Server
      properties:
         config_drive: true
         key_name: { get_param: ssh_key }
         image: cirros
         flavor: 1
         security_groups: [ ssh ]
         networks:
           - network: 'private'

outputs:
   server_id:
      value: { get_resource: nested_server }

