heat_template_version: 2015-10-15

parameters:
   net_name:
     type: string
     default: private
     description: Name of private network to be created

resources:
   myserver:
      type: OS::Nova::Server
      properties:
         config_drive: true
         key_name: 'demokey'
         image: 'cirros'
         flavor: 1
         networks:
           - network: { get_resource: mynet }

   mynet:
      type: OS::Neutron::Net
      properties:
         name: { get_param: net_name }

   mysubnet:
      type: OS::Neutron::Subnet
      properties:
         network: { get_resource: mynet }
         cidr: 10.123.123.0/24
      
outputs:
   myconsole:
      description: "How to access the server's console"
      value:
          get_attr:
            - myserver
            - console_urls
            - novnc
