heat_template_version: 2015-10-15
description: Server connected twice to the same network

resources:

   fip:
      type: OS::Neutron::FloatingIP
      properties:
         floating_network: 'public'
         port_id: { get_attr: [ myserver, addresses, private, 0, port] }

   myserver:
      type: OS::Nova::Server
      properties:
         config_drive: true
         key_name: 'demokey'
         image: 'cirros'
         flavor: 1
         networks:
           - network: private
           - network: private
         security_groups: [ 'ssh' ]

outputs:
   myip:
      description: address information of the server
      value:
         get_attr: [ myserver, addresses ]

