#cloud-config

final_message: "cloud-init { version } finished at { timestamp } processing from { datasource }"

debug:
  verbose: true

output:
  all: /home/ubuntu/cloud-config.out

runcmd:
  - [ sed, '/usedns/dI', /etc/ssh/sshd_config ]
  - 'echo "UseDNS: no" >> /etc/ssh/sshd_config'

timezone: Europe/Berlin

manage_etc_hosts: true

package:
  - wget
